version: '3.4'

services:
  tanilink_backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${TLS_CRT}
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=${TLS_KEY}
      - ASPNETCORE_Kestrel__Certificates__Default__Protocols=Http1AndHttp2
      - ConnectionStrings__DefaultConnection=${KONEKSI_DB}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__DurationInDay=${JWT_DURATION_IN_DAY}
      - MailTrap__Key=${MAILTRAP}