version: '3.4'

networks:
  tanilink-network:
    driver: bridge

services:
  tanilink-db:
    container_name: tanilink-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8011:1433
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    restart: always
    volumes:
      - tanilink-db-volume:/var/opt/mssql
    networks:
      - tanilink-network

  tanilink_backend:
    image: ${DOCKER_REGISTRY-}tanilinkbackend
    build:
      context: .
      dockerfile: TaniLink_Backend/Dockerfile
    ports:
    - 3504:80
    - 3505:443
    depends_on:
      - tanilink-db
    restart: always
    volumes:
      - tanilink-volume:/app
    networks:
      - tanilink-network

volumes:
  tanilink-volume:
  tanilink-db-volume: