version: '3.4'

services:
  tanilink_backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/bantuin.me.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/bantuin.me.key
      - ASPNETCORE_Kestrel__Certificates__Default__Protocols=Http2
    ports:
      - "80"
      - "443"