version: '3.4'

services:
  tanilink_backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/bantuin.me.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/bantuin.me.key
      - ASPNETCORE_Kestrel__Certificates__Default__Protocols=Http2
    ports:
      - "443"
      - "80"