version: '3.4'

services:
  tanilink_backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/bantuin.me.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/bantuin.me.key
    ports:
      - "443"