name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.USER_VPS }}@${{ vars.IP_VPS }} << 'EOF'
          cd ${{ vars.DIR }}
          git checkout ${{ vars.DIR }}/appsettings.json
          git pull origin master
          if [ -f bantuin.me.crt ]; then rm bantuin.me.crt; fi
          echo '${{ secrets.TLS_CRT }}' > bantuin.me.crt
          if [ -f bantuin.me.key ]; then rm bantuin.me.key; fi
          echo '${{ secrets.TLS_KEY }}' > bantuin.me.key
          if [ -f .env ]; then rm .env; fi
          echo '${{ vars.FILE_ENV }}' > .env
          if [ -f ${{ vars.DIR }}/appsettings.json ]; then rm ${{ vars.DIR }}/appsettings.json; fi
          echo '${{ vars.APP_SETTINGS }}' > ${{ vars.DIR }}/appsettings.json
          sudo docker compose build --no-cache
          sudo docker compose up -d
          cd ${{ vars.DIR }}
          dotnet ef database update
          echo 'Deployment Completed.'
        EOF